version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "monthly"
    groups:
      npm-all:
        patterns: ["*"]
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "monthly"
    groups:
      github-actions-all:
        patterns: ["*"]
    open-pull-requests-limit: 5
