name: trivy

on:
  pull_request:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read
  security-events: write

jobs:
  fs-and-config-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        continue-on-error: true
        with:
          scan-type: fs
          scan-ref: .
          format: sarif
          output: trivy-fs.sarif
          severity: HIGH,CRITICAL
          ignore-unfixed: true

      - name: Upload filesystem SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@7c1e4cf0b20d7c1872b26569c00ba908797a59bf
        with:
          sarif_file: trivy-fs.sarif
          category: trivy-fs

      - name: Trivy config scan
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        continue-on-error: true
        with:
          scan-type: config
          scan-ref: .
          format: sarif
          output: trivy-config.sarif
          severity: HIGH,CRITICAL

      - name: Upload config SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@7c1e4cf0b20d7c1872b26569c00ba908797a59bf
        with:
          sarif_file: trivy-config.sarif
          category: trivy-config
